env:
    global:
    - secure: "HBDFysj90FNmAdrziR1whg"

language: c

before_install:
    - sudo pip install codecov
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/terry_guo-gcc-arm-embedded-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
    - sudo apt-get install gcc-arm-none-eabi libcurl4-openssl-dev libelf-dev libdw-dev p7zip-full

script:
    - make extract
    - cd dsp_lib; make all; cd ..
    - make all BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

after_success:
    - bash <(curl -s https://codecov.io/bash)
